export enum QueryKeys {
  GET_CATEGORIES = "GET_CATEGORIES",
  GET_STATISTICS_TRANSACTIONS_IN_CATEGORY = "GET_STATISTICS_TRANSACTIONS_IN_CATEGORY",
  GET_STATISTICS = "GET_STATISTICS",
  GET_TRANSACTIONS = "GET_TRANSACTIONS",
  GET_TRANSACTIONS_TOTAL = "GET_TRANSACTIONS_TOTAL",
  GET_TRANSACTION = "GET_TRANSACTION",
}
